#!/usr/bin/env python3
"""
Renders the monthly metrics as a standalone image (SVG).

The image exists so the numbers can be embedded somewhere that cannot host the
page itself — e.g. an <img> on a WordPress page. It is regenerated by the same
monthly workflow that builds monthly.html, from the same data blob, so the card
and the page can never disagree.

Two constraints shape the drawing, both from the fact that this SVG is consumed
as an IMAGE rather than as a document:

* No external fonts. An SVG loaded via <img> does not fetch webfonts, and
  rsvg-convert in CI has no network either, so every font-family here is a
  stack of system faces ending in a generic. CI installs fonts-liberation so
  the PNG gets metric-compatible substitutes for Georgia/Arial.
* No text measurement. Nothing here can measure a rendered string, so the
  layout never depends on text width: every line starts at a known x, the
  delta and its context sit on separate lines rather than side by side, and
  the tiles are wide enough (442px) that the longest label — "First
  contributions made" — cannot collide with anything.
"""

SERIF = "Georgia,'Liberation Serif','DejaVu Serif',serif"
SANS = "Helvetica Neue,Helvetica,Arial,'Liberation Sans','DejaVu Sans',sans-serif"

# Mirrors the palette in monthly_template.html.
BG = "#FAF7F2"
CARD = "#ffffff"
BORDER = "#EBE5DA"
TEXT = "#23201A"
MUTED = "#756D60"
BLUE = "#3858E9"
BLUE_INK = "#2743B4"
GREEN = "#1F5C43"
RED = "#96351C"

W, H = 1000, 680
MARGIN = 48
TILE_W = 442
TILE_H = 150
GAP = 18
ROW_Y = (146, 314, 482)

MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
               "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def esc(s):
    """Escape text for XML content."""
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def month_label(key):
    y, m = key.split("-")
    return f"{MONTH_NAMES[int(m) - 1]} {y}"


def fmt_date(iso):
    if not iso:
        return "—"
    y, m, d = int(iso[0:4]), int(iso[5:7]), int(iso[8:10])
    return f"{d} {MONTH_NAMES[m - 1]} {y}"


def text(x, y, s, size, fill, family=SANS, weight="normal", extra=""):
    return (
        f'<text x="{x}" y="{y}" font-family="{family}" font-size="{size}" '
        f'font-weight="{weight}" fill="{fill}" {extra}>{esc(s)}</text>'
    )


def marker(x, y, direction, color):
    """Direction glyph, drawn as geometry rather than a character.

    ▲/▼ are missing from several of the faces this may render with, and a
    missing glyph shows as a tofu box in a PNG that nobody is watching being
    generated. Paths always draw.
    """
    if direction > 0:
        return f'<path d="M {x} {y} l 5.5 -9 l 5.5 9 z" fill="{color}"/>'
    if direction < 0:
        return f'<path d="M {x} {y - 9} l 5.5 9 l 5.5 -9 z" fill="{color}"/>'
    return f'<rect x="{x}" y="{y - 7.5}" width="9" height="7.5" rx="1.5" fill="{color}"/>'


def delta_lines(metric, previous_key):
    """The two lines under a value: the change, and what it is measured against.

    Returns (direction, colour, headline, context). Kept in step with the chip()
    function in monthly_template.html.
    """
    c = metric.get("change")
    if not c:
        return 0, MUTED, "No prior month", ""

    v = c["value"]
    color = GREEN if v > 0 else (RED if v < 0 else MUTED)
    sign = "+" if v > 0 else ""
    prev_label = month_label(previous_key)

    if c["kind"] == "points":
        headline = "No change" if v == 0 else f"{sign}{v:g} pts"
        context = f"vs {metric['previous']}% in {prev_label}"
    elif c["kind"] == "absolute":
        headline = "No change" if v == 0 else f"{sign}{v:g}"
        context = f"none recorded in {prev_label}"
    else:
        headline = "No change" if v == 0 else f"{sign}{v:g}%"
        abs_v = c.get("abs")
        context = (
            f"{'+' if abs_v and abs_v > 0 else ''}{abs_v:,} since {prev_label}"
            if abs_v is not None else f"vs {prev_label}"
        )
    return (1 if v > 0 else (-1 if v < 0 else 0)), color, headline, context


def fmt_value(metric):
    v = metric.get("value")
    if v is None:
        return "—"
    return f"{v}%" if metric.get("unit") == "percent" else f"{v:,}"


def render_svg(blob):
    """Draw the whole card and return it as an SVG string."""
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}" role="img" aria-label="{esc(card_alt_text(blob))}">',
        f'<rect width="{W}" height="{H}" fill="{BG}"/>',
    ]

    # Header
    parts.append(text(MARGIN, 54, "WORDPRESS CREDITS", 14, BLUE, SANS, "bold",
                      'letter-spacing="1.6"'))
    parts.append(text(MARGIN, 96, "Monthly metrics", 34, TEXT, SERIF, "bold"))
    asof = f"As of {fmt_date(blob.get('currentAsOf'))}  ·  compared with {fmt_date(blob.get('previousAsOf'))}"
    parts.append(text(W - MARGIN, 96, asof, 15, MUTED, SANS, "normal", 'text-anchor="end"'))
    parts.append(f'<line x1="{MARGIN}" y1="122" x2="{W - MARGIN}" y2="122" stroke="{BORDER}" stroke-width="1"/>')

    # Tiles: two per row, with the fifth spanning the full width so the grid
    # reads as deliberate rather than as a row with a hole in it.
    slots = [
        (MARGIN, ROW_Y[0], TILE_W),
        (MARGIN + TILE_W + GAP, ROW_Y[0], TILE_W),
        (MARGIN, ROW_Y[1], TILE_W),
        (MARGIN + TILE_W + GAP, ROW_Y[1], TILE_W),
        (MARGIN, ROW_Y[2], TILE_W * 2 + GAP),
    ]

    for metric, (x, y, w) in zip(blob.get("metrics", []), slots):
        parts.append(
            f'<rect x="{x}" y="{y}" width="{w}" height="{TILE_H}" rx="14" '
            f'fill="{CARD}" stroke="{BORDER}" stroke-width="1"/>'
        )
        parts.append(text(x + 24, y + 34, metric.get("label", ""), 16, MUTED, SANS, "500"))
        parts.append(text(x + 24, y + 88, fmt_value(metric), 42, BLUE_INK, SERIF, "bold"))

        direction, color, headline, context = delta_lines(metric, blob.get("previousKey", ""))
        parts.append(marker(x + 24, y + 117, direction, color))
        parts.append(text(x + 40, y + 117, headline, 16, color, SANS, "bold"))
        if context:
            parts.append(text(x + 24, y + 138, context, 13, MUTED, SANS))

    parts.append(text(
        MARGIN, H - 22,
        "Rebuilt automatically on the 1st of each month  ·  wordpress.github.io/WPCredits/monthly",
        12.5, MUTED, SANS,
    ))
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def card_alt_text(blob):
    """A one-line text equivalent, for the image's aria-label.

    An image loses the numbers for anyone using a screen reader, so the whole
    card is restated here; whoever embeds it should use this as the alt text
    too. `scripts/build_monthly.py` writes it to monthly-card.txt for that.
    """
    bits = []
    for m in blob.get("metrics", []):
        _, _, headline, _ = delta_lines(m, blob.get("previousKey", ""))
        bits.append(f"{m.get('label')} {fmt_value(m)} ({headline})")
    return (
        f"WordPress Credits monthly metrics as of {fmt_date(blob.get('currentAsOf'))}, "
        f"compared with {fmt_date(blob.get('previousAsOf'))}: " + "; ".join(bits) + "."
    )
